INSERT INTO SESSIONS (DESCRIPTION) VALUES ('Session 1');
INSERT INTO SESSIONS (DESCRIPTION) VALUES ('Session 2');
INSERT INTO SESSIONS (DESCRIPTION) VALUES ('Session 3');

INSERT INTO SPEAKERS (FIRST_NAME, LAST_NAME) VALUES ('Alice', '1');
INSERT INTO SPEAKERS (FIRST_NAME, LAST_NAME) VALUES ('Ben', '2');
INSERT INTO SPEAKERS (FIRST_NAME, LAST_NAME) VALUES ('Carl', '3');
