DROP TABLE IF EXISTS SESSIONS;
CREATE TABLE SESSIONS (
    SESSION_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(200) NOT NULL
);

DROP TABLE IF EXISTS SPEAKERS;
CREATE TABLE SPEAKERS (
    SPEAKER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(200) NOT NULL,
    LAST_NAME VARCHAR(200) NOT NULL
);